# Torch Examples

In [2]:
import torch

In [3]:
randInt = torch.randint(-100,100,(6,))
print(randInt)

tensor([-84,   6,  59, -36, -61, -35])


In [4]:
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
input = torch.empty(2,3)
input

tensor([[9.4732e-02, 8.9543e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(-10,10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

# CPU vs GPU

In [14]:
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [22]:
start_time = time.time()
zeros = torch.zeros(10000,10000)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

 0.1652765274


In [27]:
rand1 = torch.rand(100,100).to(device)
rand2 = torch.rand(100,100).to(device)
nprand1 = torch.rand(100,100)
nprand2 = torch.rand(100,100)

start_time = time.time()
# Matrix multiplication in torch
rand =  (rand1 @ rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

start_time = time.time()
# Matrix Multiplication in numpy
rand =  np.multiply(nprand1,nprand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

 0.0248465538
 0.0015099049


In [30]:
rand1 = torch.rand(10000,10000).to(device)
rand2 = torch.rand(10000,10000).to(device)
nprand1 = torch.rand(10000,10000)
nprand2 = torch.rand(10000,10000)

start_time = time.time()
# Matrix multiplication in torch
rand =  (rand1 @ rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

start_time = time.time()
# Matrix Multiplication in numpy
rand =  np.multiply(nprand1,nprand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

 0.0192470551
 0.2201814651


# More Torch functions

In [4]:
# Probability Tensor
probs = torch.tensor([0.1,0.9])

samples = torch.multinomial(probs, num_samples=10, replacement = True)
samples

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [9]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5,6,7,8])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [13]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [14]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [15]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [19]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([2,3,1])
t3 = torch.tensor([1,3,5])

print(torch.stack([t1,t3, t2]))

tensor([[1, 2, 3],
        [1, 3, 5],
        [2, 3, 1]])


In [22]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
linear(sample)

tensor([-0.9487, 12.7715,  5.4691], grad_fn=<SqueezeBackward4>)

In [24]:
import torch.nn.functional as F

tensor = torch.tensor([1., 2., 3.])
out = F.softmax(tensor, dim=0)
out

tensor([0.0900, 0.2447, 0.6652])

In [4]:
# Matrix Multiplication
tens1 = torch.tensor([[2,4],[3,5],[4,6]])
tens2 = torch.tensor([[1,2,3],[4,5,6]])

tens1 @ tens2

tensor([[18, 24, 30],
        [23, 31, 39],
        [28, 38, 48]])

# Embedding Vectors

In [28]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])

embedded_out = embedding(input_indices)
embedded_out.shape

torch.Size([4, 100])